<a href="https://colab.research.google.com/github/Hillnara/Matrizes/blob/main/Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrizes**

In [1]:
import numpy as np

In [2]:
matriz = np.array([[2,3,1],
                   [4,5,7]])

In [3]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [4]:
matriz.shape        #mostra que é uma matriz com 2 linhas e 3 colunas

(2, 3)

In [5]:
matriz[0]           # mostra a linha 0

array([2, 3, 1])

In [6]:
matriz[1]         # mostra a linha 1

array([4, 5, 7])

In [7]:
matriz[0][0]         # mostra o valor do numero da linha 0 e coluna 0

np.int64(2)

In [8]:
matriz[0][1]        # mostra o valor do numero da linha 0 e coluna 2

np.int64(3)

In [9]:
matriz[1][1]        # mostra o valor do numero da linha 1 e coluna 1

np.int64(5)

In [12]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7


1. Lista: crie uma estrutura de repetição para fazer a leitura de 5 números inteiros e os armazene dentro de uma lista. Após a leitura, crie outra estrutura de repetição para somar todos os valores digitados.

In [27]:
lista = []
for _ in range(1,6):
  valor = int(input('Digite um valor: '))
  lista.append(valor)


Digite um valor: 1
Digite um valor: 2
Digite um valor: 3
Digite um valor: 4
Digite um valor: 5


In [28]:
lista

[1, 2, 3, 4, 5]

In [31]:
soma = 0
for i in range(len(lista)):
  #print(lista[i])
  soma += lista[i]
print('Soma: ', soma)

Soma:  15


In [30]:
len(lista)      #tamanho da lista

5

In [32]:
import numpy as np
np.array(lista).sum()

np.int64(15)

2. Dicionário: Crie um dicionário para armazenar o nemo e a nota de 3 alunos, fazendo a leitura dos valores por meio de uma estrutura de repetição. depois, crie uma nova estrutura de repetição para somar todas as notas e retonar a média.

In [33]:
alunos = {}
for _ in range(1,4):
  nome = input('Digite o nome: ')
  nota = float(input('Digite a nota: '))
  alunos[nome] = nota

Digite o nome: pedro
Digite a nota: 7
Digite o nome: joao
Digite a nota: 8
Digite o nome: maria
Digite a nota: 10


In [34]:
alunos

{'pedro': 7.0, 'joao': 8.0, 'maria': 10.0}

In [35]:
alunos['joao']

8.0

In [36]:
alunos.values()

dict_values([7.0, 8.0, 10.0])

In [37]:
soma = 0
for nota in alunos.values():
  #print(nota)
  soma += nota
print('Média: ', soma / 3)

Média:  8.333333333333334


3. Matriz: dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz

matriz  np.array([[3,4,1],
                  [3,1,5]])
                  

In [38]:
matriz = np.array([[3,4,1],
                   [3,1,5]])
matriz

array([[3, 4, 1],
       [3, 1, 5]])

In [39]:
matriz.shape

(2, 3)

In [26]:
soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    #print(matriz[i][j])
    soma += matriz[i][j]
  print('Soma: ', soma)

Soma:  8
Soma:  17
